# The main pipeline for UBC Sailbot projects
pool:
  vmImage: 'Ubuntu 18.04'

steps:
- script: |
    sudo ./install_deps/install_deps_linux.sh
  displayName: 'Install deps'

  # Install an SSH key prior to a build or deployment
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJgt4KSiAbWBk2n3gRqLdhb0F1mv2fOHgrgQjScVhPaa tylergwlum@gmail.com'  # Public key can be found on github deploy keys
    #sshPassphrase: # Optional
    sshKeySecureFile: 'deployKey'  # Private key can be found on azure secure files

- task: CMake@1
  displayName: Generate Build Files
  inputs:
    workingDirectory: build
    cmakeArgs: '../'

- script: |
    ./scripts/run_cpplint.sh
  displayName: 'CPPLlint'  

- script: |
    cd build
    make all -j 4
  displayName: 'make'
  
- script: |
    cd build
    bin/run_basic_tests --gtest_output=xml
  displayName: 'Run tests'  
  
  # Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' 
    testResultsFiles: '**/*.xml' 
