# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo ./install_deps/install_deps_linux.sh
  displayName: "Install deps"

- task: CMake@1
  displayName: Generate Build Files
  inputs:
    workingDirectory: build
    cmakeArgs: '../'

- script: |
    cd build
    make
  displayName: 'make'
