# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: CMake@1
  displayName: Generate Build Files
  inputs:
    workingDirectory: build
    cmakeArgs: '../'

- task: CMake@1
  displayName: Build Solution
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)'
    cmakeArgs: '--build build --target ALL_BUILD --config Release'
